# CLI Interface with Enhanced Logging Support - Complete Implementation
# =================================================================

import argparse
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
import json

# Custom Imports
curr_path = Path(__file__).absolute()
parent_path = curr_path.parent.parent.parent.absolute()
sys.path.append(str(parent_path))

from utils.common_config import AzureOpenAIHelper, BusinessIntelligenceConfig
from ai.bi_agent.BIAgent import BusinessIntelligenceAgent

output_loc = os.getenv("OUTPUT_DIR")

# =================================================================
# CLI INTERFACE WITH COMPREHENSIVE LOGGING
# =================================================================

def setup_agent():
	"""Setup and initialize the agent"""
	try:
		print("🔧 Loading Azure OpenAI configuration...")
		config_data = AzureOpenAIHelper.setup_from_config_file()

		if not config_data:
			print("\n📋 Setup Instructions:")
			print("1. Create azure_config.json with your credentials")
			print("2. Run with --create-config to generate a sample file")
			return None

		print("🔧 Initializing configuration...")
		config = BusinessIntelligenceConfig()

		print("🧪 Testing Azure OpenAI connection...")
		if not AzureOpenAIHelper.test_azure_connection(config):
			print("❌ Azure OpenAI connection failed. Please check your configuration.")
			return None

		print("🤖 Initializing Business Intelligence Agent...")
		agent = BusinessIntelligenceAgent(config)
		print("✅ Agent initialized successfully!")

		return agent

	except Exception as e:
		print(f"❌ Setup failed: {e}")
		print("\n📋 Setup Instructions:")
		print("1. Create azure_config.json with your credentials")
		print("2. Ensure you have the required API keys")
		print("3. Check your Azure OpenAI deployment name and endpoint")
		return None


def get_user_input():
	"""Get company name and location from user"""
	print("\n" + "=" * 60)
	print("🔍 BUSINESS INTELLIGENCE RESEARCH")
	print("=" * 60)

	# Get company name
	while True:
		company_name = input("📝 Enter company name: ").strip()
		if company_name.lower() in ['quit', 'exit', 'q']:
			return None, None
		if company_name:
			break
		print("❌ Please enter a valid company name.")

	# Get location (optional)
	location = input("📍 Enter location (optional, press Enter to skip): ").strip()

	return company_name, location


def display_results(result: Dict[str, Any]):
	"""Display research results with logging info"""
	print("\n" + "=" * 80)
	if result["success"]:
		print("✅ RESEARCH COMPLETED SUCCESSFULLY")
		print("=" * 80)
		print(result["response"])
		print("\n" + "-" * 80)
		print(f"🕒 Completed: {result['timestamp']}")
		print(f"📊 Research steps: {len(result['research_steps'])}")
		print(f"📝 Session ID: {result['session_id']}")

		# Show research steps if verbose
		if result['research_steps']:
			print("\n📋 Research Steps Taken:")
			for i, step in enumerate(result['research_steps'], 1):
				print(f"  {i}. {step['tool']} - {step['timestamp'][:19]}")

		# Option to save to file
		save_option = input("\n💾 Save report to file? (y/n): ").strip().lower()
		if save_option in ['y', 'yes']:
			save_report_to_file(result, output_loc)
	else:
		print("❌ RESEARCH FAILED")
		print("=" * 80)
		print(f"Error: {result['error']}")
		print(f"📝 Session ID: {result['session_id']}")
		if result['research_steps']:
			print(f"\n📊 Research steps attempted: {len(result['research_steps'])}")


def save_report_to_file(result: Dict[str, Any], out_loc: str):
	"""Save research report to file"""
	try:
		timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
		company_safe = result['company_name'].replace(' ', '_').replace('/', '_')
		location_safe = result['location'].replace(' ', '_') if result['location'] else ""

		if location_safe:
			filename = os.path.join(out_loc,f"business_report_{company_safe}_{location_safe}_{timestamp}.txt")
		else:
			filename = os.path.join(out_loc,f"business_report_{company_safe}_{timestamp}.txt")

		with open(filename, 'w', encoding='utf-8') as f:
			f.write("BUSINESS INTELLIGENCE REPORT\n")
			f.write("=" * 50 + "\n")
			f.write(f"Company: {result['company_name']}\n")
			f.write(f"Location: {result['location'] or 'Not specified'}\n")
			f.write(f"Generated: {result['timestamp']}\n")
			f.write(f"Session ID: {result['session_id']}\n")
			f.write(f"Research Steps: {len(result['research_steps'])}\n")
			f.write("=" * 50 + "\n\n")
			f.write(result["response"])
			f.write(f"\n\n{'=' * 50}\n")
			f.write("Report generated by Business Intelligence AI Agent\n")

			# Add research steps details
			if result['research_steps']:
				f.write(f"\n{'=' * 50}\n")
				f.write("RESEARCH STEPS TAKEN:\n")
				f.write(f"{'=' * 50}\n")
				for i, step in enumerate(result['research_steps'], 1):
					f.write(f"{i}. Tool: {step['tool']}\n")
					f.write(f"   Input: {step['input']}\n")
					f.write(f"   Time: {step['timestamp']}\n\n")

		print(f"✅ Report saved to: {filename}")

		# Show file info
		file_size = Path(filename).stat().st_size
		print(f"📄 File size: {file_size:,} bytes")
		print(f"📂 Full path: {Path(filename).absolute()}")

	except Exception as e:
		print(f"❌ Failed to save file: {e}")


def show_cached_companies(agent: BusinessIntelligenceAgent):
	"""Show list of cached companies"""
	cached_companies = agent.cache_manager.list_cached_companies()

	if not cached_companies:
		print("📭 No cached companies found.")
		return

	print(f"\n📋 Cached Companies ({len(cached_companies)} total):")
	print("=" * 80)

	for company in cached_companies:
		status = "❌ EXPIRED" if company["expired"] else "✅ VALID"
		location_text = f" ({company['location']})" if company['location'] else ""
		print(f"{status} {company['company_name']}{location_text}")
		print(f"        Updated: {company['updated_at'][:19]} ({company['age_hours']}h ago)")
		print()


def show_agent_logs(agent: BusinessIntelligenceAgent):
	"""Show list of agent execution logs"""
	log_files = agent.get_log_files()

	if not log_files:
		print("📭 No agent logs found.")
		return

	print(f"\n📋 Agent Execution Logs ({len(log_files)} total):")
	print("=" * 100)
	print(f"{'#':<3} {'Company':<25} {'Date':<12} {'Time':<10} {'Size':<10} {'Session ID':<30}")
	print("-" * 100)

	for i, log_file in enumerate(log_files[:20], 1):  # Show latest 20
		size_str = f"{log_file['size_bytes']:,}B"
		session_id = log_file['filename'].replace('agent_log_', '').replace('.json', '')
		print(
			f"{i:<3} {log_file['company'][:24]:<25} {log_file['date']:<12} {log_file['time']:<10} {size_str:<10} {session_id[:29]:<30}")

	if len(log_files) > 20:
		print(f"\n... and {len(log_files) - 20} more logs. Use --view-log <session_id> to view specific logs.")


def view_specific_log(agent: BusinessIntelligenceAgent, session_id: str):
	"""View a specific agent log"""
	log_data = agent.view_log_file(session_id)

	if not log_data:
		print(f"❌ Could not find or read log for session: {session_id}")
		return

	print(f"\n📋 AGENT EXECUTION LOG: {session_id}")
	print("=" * 100)
	print(f"Search Term: {log_data['search_term']}")
	print(f"Location: {log_data['location'] or 'Not specified'}")
	print(f"Duration: {log_data.get('duration_seconds', 0):.2f} seconds")
	print(f"Success: {log_data.get('success', False)}")
	print(f"Total Tool Calls: {len(log_data['tool_calls'])}")

	# Show agent chain log summary
	print(f"\n📊 EXECUTION CHAIN SUMMARY:")
	print("-" * 50)
	for i, log_entry in enumerate(log_data['agent_chain_log'], 1):
		entry_type = log_entry['type'].upper()
		timestamp = log_entry['timestamp'][:19]

		if log_entry['type'] == 'action':
			print(f"{i}. {entry_type}: {log_entry['tool']} ({timestamp})")
		else:
			print(f"{i}. {entry_type} ({timestamp})")

	# Ask if user wants to see full details
	show_full = input(f"\n🔍 View full log details? (y/n): ").strip().lower()
	if show_full in ['y', 'yes']:
		print(f"\n📋 FULL AGENT CHAIN LOG:")
		print("-" * 80)

		for i, log_entry in enumerate(log_data['agent_chain_log'], 1):
			print(f"\nStep {i}: {log_entry['type'].upper()}")
			print(f"Time: {log_entry['timestamp']}")

			if log_entry['type'] == 'action':
				print(f"Tool: {log_entry['tool']}")
				print(f"Input: {log_entry['tool_input']}")
				if log_entry.get('observation'):
					obs = log_entry['observation']
					if len(obs) > 500:
						print(f"Observation: {obs[:500]}... [truncated]")
					else:
						print(f"Observation: {obs}")
			elif log_entry['type'] == 'finish':
				output = log_entry['return_values'].get('output', '')
				if len(output) > 500:
					print(f"Final Output: {output[:500]}... [truncated]")
				else:
					print(f"Final Output: {output}")

			print("-" * 40)


def interactive_mode(agent: BusinessIntelligenceAgent):
	"""Run the agent in interactive mode"""
	print("🚀 Starting Interactive Business Intelligence Research")
	print("💡 Commands: 'quit', 'exit', 'q' to stop")
	print("💡 Special commands: 'cache', 'logs', 'clear'")

	while True:
		try:
			# Check for special commands
			command = input("\n📝 Enter company name (or command): ").strip()

			if command.lower() in ['quit', 'exit', 'q']:
				print("👋 Goodbye!")
				break
			elif command.lower() == 'cache':
				show_cached_companies(agent)
				continue
			elif command.lower() == 'logs':
				show_agent_logs(agent)

				# Ask if they want to view a specific log
				view_log = input("\n🔍 View specific log? Enter session ID (or press Enter to continue): ").strip()
				if view_log:
					view_specific_log(agent, view_log)
				continue
			elif command.lower() == 'clear':
				agent.clear_memory()
				print("🧹 Conversation memory cleared.")
				continue
			elif command.lower().startswith('view-log '):
				session_id = command.replace('view-log ', '').strip()
				view_specific_log(agent, session_id)
				continue
			elif not command:
				continue

			# Get location
			location = input("📍 Enter location (optional): ").strip()

			print(f"\n🔍 Researching: {command}")
			if location:
				print(f"📍 Location: {location}")

			# Perform research
			result = agent.research_business(command, location)
			display_results(result)

		except KeyboardInterrupt:
			print("\n\n👋 Interrupted by user. Goodbye!")
			break
		except Exception as e:
			print(f"\n❌ An error occurred: {e}")


def batch_mode(agent: BusinessIntelligenceAgent, companies_file: str):
	"""Run the agent in batch mode from a file"""
	try:
		with open(companies_file, 'r', encoding='utf-8') as f:
			companies = [line.strip() for line in f if line.strip() and not line.startswith('#')]

		print(f"📋 Processing {len(companies)} companies from {companies_file}")

		results = []
		for i, company_line in enumerate(companies, 1):
			# Parse company and location
			if '|' in company_line:
				company_name, location = company_line.split('|', 1)
				company_name = company_name.strip()
				location = location.strip()
			else:
				company_name = company_line.strip()
				location = ""

			print(f"\n[{i}/{len(companies)}] Researching: {company_name}")
			if location:
				print(f"📍 Location: {location}")

			result = agent.research_business(company_name, location)
			results.append(result)

			if result["success"]:
				print(f"✅ Success (Session: {result['session_id']})")
			else:
				print(f"❌ Failed: {result['error']} (Session: {result['session_id']})")

			# Save individual report
			save_report_to_file(result, output_loc)

			# Small delay between requests
			time.sleep(2)

		# Summary
		successful = sum(1 for r in results if r["success"])
		print(f"\n📊 Batch processing complete:")
		print(f"✅ Successful: {successful}/{len(companies)}")
		print(f"❌ Failed: {len(companies) - successful}/{len(companies)}")

		# Show session IDs for failed ones
		failed_sessions = [r['session_id'] for r in results if not r['success']]
		if failed_sessions:
			print(f"\n❌ Failed session IDs (use --view-log to investigate):")
			for session_id in failed_sessions:
				print(f"   📝 {session_id}")

		# Show all session IDs for reference
		print(f"\n📝 All session IDs from this batch:")
		for r in results:
			status = "✅" if r['success'] else "❌"
			print(f"   {status} {r['session_id']} - {r['company_name']}")

	except FileNotFoundError:
		print(f"❌ File not found: {companies_file}")
	except Exception as e:
		print(f"❌ Batch processing error: {e}")


def export_logs_summary(agent: BusinessIntelligenceAgent, output_file: str = None):
	"""Export a summary of all logs to a file"""
	try:
		log_files = agent.get_log_files()

		if not log_files:
			print("📭 No logs to export.")
			return

		if not output_file:
			timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
			output_file = f"agent_logs_summary_{timestamp}.json"

		# Create summary data
		summary = {
			"export_date": datetime.now().isoformat(),
			"total_logs": len(log_files),
			"logs": []
		}

		for log_file in log_files:
			# Try to read the full log for additional stats
			try:
				full_log = agent.view_log_file(log_file['filename'].replace('agent_log_', '').replace('.json', ''))
				if full_log:
					log_summary = {
						"session_id": full_log['session_id'],
						"company": full_log['search_term'],
						"location": full_log['location'],
						"success": full_log.get('success', False),
						"duration_seconds": full_log.get('duration_seconds', 0),
						"total_tool_calls": len(full_log['tool_calls']),
						"tools_used": list(set([call['tool'] for call in full_log['tool_calls']])),
						"start_time": full_log['start_time'],
						"end_time": full_log['end_time'],
						"has_errors": bool(full_log.get('error_log', ''))
					}
					summary['logs'].append(log_summary)
			except Exception:
				# If we can't read the full log, use basic info
				session_id = log_file['filename'].replace('agent_log_', '').replace('.json', '')
				basic_summary = {
					"session_id": session_id,
					"company": log_file['company'],
					"file_size_bytes": log_file['size_bytes'],
					"modified": log_file['modified'],
					"error": "Could not read full log details"
				}
				summary['logs'].append(basic_summary)

		# Save summary
		with open(output_file, 'w', encoding='utf-8') as f:
			json.dump(summary, f, indent=2, ensure_ascii=False)

		print(f"✅ Logs summary exported to: {output_file}")
		print(f"📊 Total logs: {len(log_files)}")

		# Show some basic stats
		if summary['logs']:
			successful = sum(1 for log in summary['logs'] if log.get('success', False))
			avg_duration = sum(log.get('duration_seconds', 0) for log in summary['logs']) / len(summary['logs'])
			print(
				f"📈 Success rate: {successful}/{len(summary['logs'])} ({successful / len(summary['logs']) * 100:.1f}%)")
			print(f"⏱️  Average duration: {avg_duration:.2f} seconds")

	except Exception as e:
		print(f"❌ Failed to export logs summary: {e}")


def main():
	"""Main CLI function with comprehensive logging support"""
	parser = argparse.ArgumentParser(
		description="Business Intelligence AI Agent with Comprehensive Logging",
		epilog="""
				Examples:
				  %(prog)s                                    # Interactive mode
				  %(prog)s --company Apple --location USA     # Single company research
				  %(prog)s --batch companies.txt              # Batch processing
				  %(prog)s --logs                            # View all execution logs
				  %(prog)s --view-log 20250603_145230_apple  # View specific log
				  %(prog)s --cache                           # View cached companies
				  %(prog)s --export-logs                     # Export logs summary
						""", formatter_class=argparse.RawDescriptionHelpFormatter)

	parser.add_argument("--create-config", action="store_true",
						help="Create a sample configuration file")
	parser.add_argument("--batch", type=str, metavar="FILE",
						help="Run in batch mode with companies from file")
	parser.add_argument("--company", type=str, help="Company name to research")
	parser.add_argument("--location", type=str, help="Company location")
	parser.add_argument("--cache", action="store_true",
						help="Show cached companies and exit")
	parser.add_argument("--logs", action="store_true",
						help="Show agent execution logs and exit")
	parser.add_argument("--view-log", type=str, metavar="SESSION_ID",
						help="View specific agent log by session ID")
	parser.add_argument("--export-logs", type=str, nargs='?', const='auto', metavar="OUTPUT_FILE",
						help="Export logs summary to JSON file (auto-generated filename if not specified)")

	args = parser.parse_args()

	# Handle create config
	if args.create_config:
		AzureOpenAIHelper.create_sample_config()
		return

	# Setup agent (required for all other operations)
	agent = setup_agent()
	if not agent:
		return

	# Handle logs export
	if args.export_logs:
		output_file = None if args.export_logs == 'auto' else args.export_logs
		export_logs_summary(agent, output_file)
		return

	# Handle logs view
	if args.logs:
		show_agent_logs(agent)
		return

	# Handle specific log view
	if args.view_log:
		view_specific_log(agent, args.view_log)
		return

	# Handle cache view
	if args.cache:
		show_cached_companies(agent)
		return

	# Handle single company research
	if args.company:
		print(f"🔍 Researching: {args.company}")
		if args.location:
			print(f"📍 Location: {args.location}")

		result = agent.research_business(args.company, args.location or "")
		display_results(result)
		return

	# Handle batch mode
	if args.batch:
		batch_mode(agent, args.batch)
		return

	# Interactive mode (default)
	interactive_mode(agent)


if __name__ == "__main__":
	try:
		main()
	except KeyboardInterrupt:
		print("\n\n👋 Interrupted by user. Goodbye!")
	except Exception as e:
		print(f"\n❌ Fatal error: {e}")
		import traceback

		traceback.print_exc()